en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Buckhannon & Tygart Valley River Water Trail. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "BTV River Water Trail"
  params:
    description: "Buckhannon & Tygart Valley River Water Trail"
    ### accessibility ###
    #accessibility:
    #  skip_text: "Skip to content"
    #  help_text: "Accessibility Statement"
    #  help_url: "/example-page/"
    #### calls to action ###
    main_cta:
      text: "Get the newsletter"
      link: "/newsletter/"
    footer_cta:
      text: "Get the newsletter"
      link: "/newsletter/"
    #github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "plan"
      name: "Plan"
      weight: 1
    - identifier: "access-maps-guides"
      name: "Access Sites, Maps, & Guides"
      url: "/access-maps-guides/"
      weight: 1
      parent: "plan"
    - identifier: "trips"
      name: "Recommended Trips"
      url: "/trips/"
      weight: 2
      parent: "plan"
    - identifier: "hazards-water-levels"
      name: "Hazards & Water Levels"
      url: "/hazards-water-levels/"
      weight: 3
      parent: "plan"
    - identifier: "leave-no-trace"
      name: "Practice Leave No Trace"
      url: "/leave-no-trace/"
      weight: 4
      parent: "plan"
    - identifier: "along-way"
      name: "Along the Way"
      url: "/along-way/"
      weight: 5
      parent: "plan"
    - identifier: "rentals-shuttles"
      name: "Kayak Rentals & Shuttle Services"
      url: "/rentals-shuttles/"
      weight: 6
      parent: "plan"
    #
    #
    #
    - identifier: "get-involved"
      name: "Get Involved"
      weight: 2
    - identifier: "newsletter"
      name: "Newsletter"
      url: "/newsletter/"
      weight: 1
      parent: "get-involved"
    - identifier: "stewardship"
      name: "Stewardship Opportunities"
      url: "/stewardship/"
      weight: 2
      parent: "get-involved"
    - identifier: "donate"
      name: "Donate"
      url: "/donate/"
      weight: 3
      parent: "get-involved" 
    #
    #
    #
    - identifier: "learn"
      name: "Learn"
      url: "/learn/"
      weight: 3
    #
    #
    #
    - identifier: "events"
      name: "Events"
      url: "/events/"
      weight: 4
    #
    #
    #
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 5
#es:
#  languageName: Spanish
#  contentDir: content/es
#  weight: 2
#  title: "Título del Sitio"
#  params:
#    description: "Descripción del Sitio"
#  menu:
#    main:
#    - identifier: "about"
#      name: "Acerca de"
#      url: "/example-page/"
#      weight: 1
#    - identifier: "child-1"
#      name: "Página Hija de Ejemplo"
#      url: "/example-page/"
#      weight: 1
#      parent: "about"
#    - identifier: "faq"
#      name: "FAQs"
#      url: "/faq/"
#      weight: 3
#    - identifier: "blog"
#      name: "Blog"
#      url: "/blog/"
#      weight: 2
