* Images
https://www.svgrepo.com/svg/38944/river
publicdomainpictures.net

* Licenses
https://github.com/sytranvn/hugo-pdf/tree/master - MIT

* TODO
- are these people cool with having their images on the site? no permissions yet
- alt tags
- accessibility checkup
- more images for specific events?
- donations
- contact form - which email address should messages go to?

* webp
find . -type f \( -iname '*.png' -o -iname '*.HEIC' -o -iname '*.jpg' -o -iname '*.jpeg' \) -exec sh -c 'cwebp -quiet "$1" -o "${1%.*}.webp"' _ {} \;



map and guide as own dropdown


card with link to map above or below discover on homepage


for map and guide put all access sites in one table with pics, let the pdfs be the sections. possibly get pics with all access sites and incorporate them into table


google mind map page with interactive maps and links to earthviews


bios for stewardship page - promote next year's cohort with a landing page


towards bottom of home page or own page: local businesses buy promotion


take down stewardship image


events page will link to sub-events page


events will need specific year landing pages and generic pages


invoice
