######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: "https://btvwatertrail.org"
googleAnalytics:
enableRobotsTXT: true
build:
  writeStats: true
